name: SSH Connection and Build

on:
  push:
    branches:
      - master  # 替换为你希望触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.jenkins }}

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run build.sh script
        run: |
          ssh root@139.159.234.134 "ls && cd /path/to/repository && sh build.sh"
